/* Brysen Allen, Joe Davidson, Grace Crockett, David Pesin
   DB-Project
*/
CREATE TABLE PASSENGER (
	PASS_ID       Numeric(7,0) PRIMARY KEY,
	PASS_NAME     VARCHAR(20) NOT NULL,
	PASS_LNAME    VARCHAR(20) NOT NULL,
	PASS_STREET   VARCHAR(20) NOT NULL,
	PASS_CITY     VARCHAR(20) NOT NULL,
	PASS_STATE    VARCHAR(20) NOT NULL,
	PASS_ZIP      INT(10) UNSIGNED NOT NULL,
	PASS_COUNTRY  VARCHAR(20) NOT NULL
  );

CREATE TABLE INVOICE(
  INV_ID      NUMERIC(7,0) PRIMARY KEY,
  PRICE       NUMERIC(5,2) NOT NULL,
  CONF_CODE   VARCHAR(20) NOT NULL,
  FOREIGN KEY(PASS_ID) REFERNCES PASSENGER(PASS_ID)
  );

CREATE TABLE TICKET(
  TICKET_ID     NUMERIC(7,0) PRIMARY KEY,
  FOREIGN KEY   (ROUTE_ASSIGN) 
  SEAT_NUM      VARCHAR(6)
  FOREIGN KEY(INV_ID) REFERENCES INVOICE(INV_ID)
  );

CREATE TABLE ROUTE(
  ROUTE_NUM   NUMERIC(3,0) PRIMARY KEY,
  FOREIGN KEY (TRAIN_NUM)
  EST_DEPT
  EST_ARRIVAL
  );

CREATE TABLE STOPS(
  FOREIGN KEY(ROUTE_NUM)
  FOREIGN KEY(STAT_NUM)
  STOP_NUM
  );
  
CREATE TABLE STATION(
  STAT_NUM      PRIMARY KEY
  STAT_STREET   VARCHAR(20) NOT NULL,
	STAT_CITY     VARCHAR(20) NOT NULL,
	STAT_STATE    VARCHAR(20) NOT NULL,
	STAT_ZIP      INT(10) UNSIGNED NOT NULL,
	STAT_COUNTRY  VARCHAR(20) NOT NULL
  );
 
CREATE TABLE STATION_ASSGN(
  STAT_ASSGN PRIMARY KEY
  FOREIGN KEY(EMP_NUM)
  FOREIGN KEY(STAT_NUM)
  START_DATE
  END_DATE
  );

CREATE TABLE EMPLOYEE(
  EMP_ID PRIMARY KEY
  EMP_FNAME
  EMP_LNAME
  EMP_HIREDATE
  FOREIGN KEY(JOB_CODE)
  REPORTS_T0
  );
  
CREATE TABLE TRAIN(
  TRAIN_NUM PRIMARY KEY
  CONDUCTOR_ID
  NUM_SEATS
  );

CREATE TABLE TRAIN_ASSGN(
  T_ASSGN PRIMARY KEY
  FOREIGN KEY(EMP_ID)
  FOREIGN KEY(TRAIN_NUM)
  START_DATE
  END_DATE
  );
  
CREATE TABLE ENGINE(
  ENG_NUM PRIMARY KEY
  ENG_MODEL
  ENG_DESC
  );
  
CREATE TABLE ENGINE_ASSGN(
  E_ASSGN PRIMARY KEY
  FOREIGN KEY(ENG_NUM)
  FOREIGN KEY(TRAIN_NUM)
  START_DATE
  END_DATE
  );
  
CREATE TABLE CAR(
  CAR_NUM PRIMARY KEY
  CAR_DESC
  CAR_CAPACITY
  );
  
CREATE TABLE CAR_ASSGN
  C_ASSGN PRIMARY KEY
  FOREIGN KEY(CAR_NUM)
  FOREIGN KEY(TRAIN_NUM)
  START_DATE
  END_DATE
  );
  
CREATE TABLE JOB(
  JOB_CODE PRIMARY KEY
  JOB_DESC
  JOB_TITLE
  );
  
CREATE TABLE MEHCANIC(
  FOREIGN KEY(EMP_ID)
  CERT_DATE
  CERT_EXP
  );
  
CREATE TABLE CONDUCTOR
  FOREIGN KEY(EMP_NUM)
  CERT_DATE
  CERT_EXP
  );