/* Brysen Allen, Joe Davidson, Grace Crockett, David Pesin
   DB-Project
*/
CREATE TABLE PASSENGER (
	PASS_ID       Numeric(7,0) PRIMARY KEY,
	PASS_NAME     VARCHAR(20) NOT NULL,
	PASS_LNAME    VARCHAR(20) NOT NULL,
	PASS_STREET   VARCHAR(20) NOT NULL,
	PASS_CITY     VARCHAR(20) NOT NULL,
	PASS_STATE    VARCHAR(20) NOT NULL,
	PASS_ZIP      NUMERIC(10,0) NOT NULL,
	PASS_COUNTRY  VARCHAR(20) NOT NULL
  );

CREATE TABLE INVOICE(
  INV_ID      NUMERIC(7,0) PRIMARY KEY,
  PRICE       NUMERIC(5,2) NOT NULL,
  CONF_CODE   VARCHAR(20) NOT NULL,
  FOREIGN KEY(PASS_ID) REFERNCES PASSENGER(PASS_ID)
  );

CREATE TABLE TICKET(
  TICKET_ID     NUMERIC(7,0) PRIMARY KEY,
  FOREIGN KEY   (ROUTE_ASSIGN) 
  SEAT_NUM      VARCHAR(6)
  FOREIGN KEY(INV_ID) REFERENCES INVOICE(INV_ID)
  );
  
CREATE TABLE TRAIN(
TRAIN_NUM PRIMARY KEY
CONDUCTOR_ID	NUMERIC(7,0) NOT NULL
NUM_SEATS	NUMERIC(7,0) NOT NULL
);

CREATE TABLE ROUTE(
  ROUTE_NUM   NUMERIC(3,0) PRIMARY KEY,
  FOREIGN KEY (TRAIN_NUM) REFERENCES TRAIN(TRAIN_NUM)
  );
  
CREATE TABLE ROUTE_ASSGN(
  R_ASGN	NUMERIC(7,0) PRIMARY KEY
  FOREIGN KEY (ROUTE_NUM) REFERENCES ROUTE(ROUTE_NUM)
  TRUE_DEPT	DATE
  TRUE_ARR	DATE
  EST_DEPT	DATE
  EST_ARRIVAL	DATE
  );

CREATE TABLE STATION(
STAT_NUM      PRIMARY KEY
STAT_STREET   VARCHAR(20) NOT NULL,
STAT_CITY     VARCHAR(20) NOT NULL,
STAT_STATE    VARCHAR(20) NOT NULL,
STAT_ZIP      INT(10) UNSIGNED NOT NULL,
STAT_COUNTRY  VARCHAR(20) NOT NULL
);

CREATE TABLE STOPS(
  FOREIGN KEY(ROUTE_NUM) REFERENCES ROUTE(ROUTE_NUM)
  FOREIGN KEY(STAT_NUM) REFERENCES STATION(STAT_NUM)
  STOP_NUM	NUMERIC(3,0)
  );
  
CREATE TABLE EMPLOYEE(
  EMP_ID PRIMARY KEY
  EMP_FNAME	VARCHAR(20)
  EMP_LNAME	VARCHAR(20)
  EMP_HIREDATE	DATE NOT NULL
  FOREIGN KEY(JOB_CODE)
  REPORTS_T0	FOREIGN ## FIX THIS W RECURSIVE SETUP##############################################################
  );
 
CREATE TABLE STATION_ASSGN(
  STAT_ASSGN PRIMARY KEY
  FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
  FOREIGN KEY(STAT_NUM) REFERENCES STATION(STAT_NUM)
  START_DATE	DATE NOT NULL
  END_DATE	DATE
  );


  


CREATE TABLE TRAIN_ASSGN(
  T_ASSGN PRIMARY KEY
  FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
  FOREIGN KEY(TRAIN_NUM) REFERENCES TRAIN(TRAIN_NUM)
  START_DATE	DATE NOT NULL
  END_DATE	DATE 
  );
  
CREATE TABLE ENGINE(
  ENG_NUM PRIMARY KEY
  ENG_MODEL	VARCHAR(20) NOT NULL
  ENG_DESC	VARCHAR(50) NOT NULL
  );
  
CREATE TABLE ENGINE_ASSGN(
  E_ASSGN PRIMARY KEY
  FOREIGN KEY(ENG_NUM) REFERENCES ENGINE(ENG_NUM)
  FOREIGN KEY(TRAIN_NUM)
  START_DATE	DATE NOT NULL
  END_DATE	DATE 
  );
  
CREATE TABLE CAR(
  CAR_NUM PRIMARY KEY 
  CAR_DESC	VARCHAR(20) NOT NULL
  CAR_CAPACITY	NUMERIC(7,0) NOT NULL
  );
  
CREATE TABLE CAR_ASSGN
  C_ASSGN PRIMARY KEY
  FOREIGN KEY(CAR_NUM) REFERENCES CAR(CAR_NUM)
  FOREIGN KEY(TRAIN_NUM) REFERENCES TRAIN(TRAIN_NUM)
  START_DATE DATE NOT NULL
  END_DATE   DATE 
  );
  
CREATE TABLE JOB(
  JOB_CODE PRIMARY KEY
  JOB_DESC	VARCHAR(20) NOT NULL
  JOB_TITLE	VARCHAR(20) NOT NULL
  );
  
CREATE TABLE MEHCANIC(
  FOREIGN KEY(EMP_ID) REFERENCES EMPLOYE(EMP_ID)
  CERT_DATE	VARCHAR(20) NOT NULL
  CERT_EXP	VARCHAR(20) NOT NULL
  );
  
CREATE TABLE CONDUCTOR
  FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
  CERT_DATE	DATE NOT NULL
  CERT_EXP	DATE NOT NULL
  );
  
